typography_spectrum: 0.4745118566788733
color:
  brandStrength: 0.34437449206598103
  lightness: 0.9476922731846571
  saturation: 0.7220902766566724
  rhythmicContrast: 0.29849408636800945
layout_spectrum: 0.229532242519781
name: >-
  MISSION - a strongly felt aim, ambition or calling; WARY - feeling or showing
  caution about possible dangers or problems
title: Why we all need to be wary of Missions
description: (and I can say this because I'm a missionary)
